spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Priyanshujain05/hotel-rating-microservice-configurations
          clone-on-start: true
        composite:
          - type: git
            uri: https://github.com/Priyanshujain05/hotel-rating-microservice-configurations
          - type: classpath
            resource: application.yml
      bootstrap: true
  server:
    port: 8084
